<?php

return [
    'categories' => [
        'technology' => [
            'id' => 'technology',
            'name' => 'Technology',
            'description' => 'Software, hardware, programming, tech industry news',
            'seed_urls' => [
                'https://cnet.com/news',
                'https://techspot.com',
                'https://theverge.com',
                'https://wired.com/category/science',
                'https://zdnet.com',
                'https://arstechnica.com',
                'https://techcrunch.com',
                'https://engadget.com',
                'https://gizmodo.com',
                'https://mashable.com/tech',
                'https://thenextweb.com',
                'https://venturebeat.com',
                'https://slashdot.org',
                'https://hackaday.com',
                'https://tomshardware.com',
                'https://anandtech.com',
                'https://pcmag.com',
                'https://digitaltrends.com',
                'https://techmeme.com',
                'https://recode.net',
            ],
            'keywords' => ['tech', 'technology', 'software', 'hardware', 'computer', 'device', 'gadget', 'app', 'platform', 'digital', 'innovation', 'startup', 'developer', 'programming', 'code', 'cloud', 'data', 'cyber', 'internet', 'web'],
        ],
        'business' => [
            'id' => 'business',
            'name' => 'Business',
            'description' => 'Finance, markets, entrepreneurship, corporate news',
            'seed_urls' => [
                'https://businessinsider.com',
                'https://cnbc.com/id/10001147',
                'https://economist.com',
                'https://forbes.com/business',
                'https://entrepreneur.com',
                'https://bloomberg.com',
                'https://wsj.com',
                'https://ft.com',
                'https://reuters.com/business',
                'https://marketwatch.com',
                'https://fortune.com',
                'https://inc.com',
                'https://fastcompany.com',
                'https://barrons.com',
                'https://investopedia.com',
                'https://seekingalpha.com',
                'https://fool.com',
                'https://morningstar.com',
                'https://benzinga.com',
                'https://thestreet.com',
            ],
            'keywords' => ['business', 'finance', 'market', 'stock', 'trade', 'invest', 'economy', 'corporate', 'company', 'startup', 'entrepreneur', 'ceo', 'revenue', 'profit', 'merger', 'acquisition', 'ipo', 'venture', 'capital', 'fund'],
        ],
        'ai' => [
            'id' => 'ai',
            'name' => 'AI',
            'description' => 'Artificial intelligence, machine learning, AI research and applications',
            'seed_urls' => [
                'https://venturebeat.com/ai',
                'https://technologyreview.com/topic/artificial-intelligence',
                'https://aitrends.com',
                'https://syncedreview.com',
                'https://towardsdatascience.com',
                'https://deepmind.com/blog',
                'https://openai.com/blog',
                'https://ai.google/research',
                'https://research.facebook.com/ai',
                'https://blogs.microsoft.com/ai',
                'https://machinelearningmastery.com',
                'https://kdnuggets.com',
                'https://analyticsvidhya.com',
                'https://medium.com/topic/artificial-intelligence',
                'https://arxiv.org/list/cs.AI/recent',
                'https://aiweekly.co',
                'https://twimlai.com',
                'https://lexfridman.com/ai',
                'https://thegradient.pub',
                'https://distill.pub',
            ],
            'keywords' => ['ai', 'artificial', 'intelligence', 'machine', 'learning', 'deep', 'neural', 'network', 'model', 'algorithm', 'llm', 'gpt', 'chatbot', 'nlp', 'computer', 'vision', 'robotics', 'automation', 'data', 'science'],
        ],
        'sports' => [
            'id' => 'sports',
            'name' => 'Sports',
            'description' => 'All sports news, events, and analysis',
            'seed_urls' => [
                'https://espn.com',
                'https://bbc.com/sport',
                'https://theguardian.com/sport',
                'https://si.com',
                'https://nbcsports.com',
                'https://cbssports.com',
                'https://bleacherreport.com',
                'https://sbnation.com',
                'https://skysports.com',
                'https://foxsports.com',
                'https://theathletic.com',
                'https://sportingnews.com',
                'https://yahoo.com/sports',
                'https://nfl.com',
                'https://nba.com',
                'https://mlb.com',
                'https://nhl.com',
                'https://fifa.com',
                'https://uefa.com',
                'https://formula1.com',
            ],
            'keywords' => ['sport', 'sports', 'game', 'match', 'team', 'player', 'athlete', 'football', 'soccer', 'basketball', 'baseball', 'hockey', 'tennis', 'golf', 'racing', 'f1', 'nfl', 'nba', 'mlb', 'nhl'],
        ],
        'politics' => [
            'id' => 'politics',
            'name' => 'Politics',
            'description' => 'Political news, policy, elections, government',
            'seed_urls' => [
                'https://politico.com',
                'https://thehill.com',
                'https://bbc.com/news/politics',
                'https://apnews.com/politics',
                'https://vox.com/politics',
                'https://cnn.com/politics',
                'https://nytimes.com/section/politics',
                'https://washingtonpost.com/politics',
                'https://reuters.com/politics',
                'https://theguardian.com/politics',
                'https://axios.com/politics-policy',
                'https://rollcall.com',
                'https://fivethirtyeight.com',
                'https://realclearpolitics.com',
                'https://nationalreview.com',
                'https://theatlantic.com/politics',
                'https://newrepublic.com',
                'https://slate.com/news-and-politics',
                'https://motherjones.com',
                'https://propublica.org',
            ],
            'keywords' => ['politic', 'politics', 'government', 'election', 'vote', 'congress', 'senate', 'president', 'minister', 'parliament', 'policy', 'law', 'legislation', 'campaign', 'democrat', 'republican', 'party', 'candidate', 'debate', 'reform'],
        ],
    ],

    'valid_categories' => ['technology', 'business', 'ai', 'sports', 'politics'],
];
